name: vimix
base: core24
version: '0.8.5'
summary: Video live mixer
title: vimix
description: |
   vimix performs graphical mixing and blending of several movie clips and
   computer generated graphics, with image processing effects in real-time.
   Its intuitive and hands-on user interface gives direct control on image opacity and
   shape for producing live graphics during concerts and VJ-ing sessions.
   The ouput image is typically projected full-screen on an external
   monitor or a projector, but can be recorded and streamed live (no audio).
contact: https://brunoherbelin.github.io/vimix/
website: https://github.com/brunoherbelin/vimix
issues: https://github.com/brunoherbelin/vimix/issues
source-code: https://github.com/brunoherbelin/vimix.git
icon: snap/gui/vimix.svg
license: GPL-3.0+
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
platforms:
  amd64:
  armhf:
  arm64:
  
layout:
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu/X11/XErrorDB
    
plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
    
apps:
  vimix:
    extensions: [gnome]
    command-chain:
      - bin/gpu-2404-wrapper
    command: usr/bin/launch_vimix.sh
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - wayland
      - x11
      - home
      - network
      - camera
      - raw-usb
      - removable-media
      - audio-playback
      - shared-memory
      - joystick
      - screencast-legacy
    environment:
       GST_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gstreamer-1.0
       GST_PLUGIN_SYSTEM_PATH : $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gstreamer-1.0
       GST_PLUGIN_SCANNER: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
       FREI0R_PATH: $SNAP/usr/lib/frei0r-1
       LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack

parts:
  vimix-binary:
    plugin: cmake
    source: .
    cmake-parameters:
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    build-packages:
    -  g++
    -  make
    -  git
    -  libpng-dev
    -  libxrandr-dev
    -  libglfw3-dev
    -  libgstreamer1.0-dev
    -  libgstreamer-plugins-base1.0-dev
    -  libicu-dev
    -  ableton-link-dev
    -  libtinyxml2-dev
    -  libglm-dev
    -  execstack
    stage-packages:
    -  libglu1-mesa
    -  libblas3
    -  liblapack3
    -  libglfw3
    -  frei0r-plugins
    -  libgstreamer1.0-0
    -  libgstreamer-gl1.0-0
    -  libgstreamer-plugins-base1.0-0
    -  libgstreamer-plugins-good1.0-0
    -  libgstreamer-plugins-bad1.0-0
    -  gstreamer1.0-libav
    -  gstreamer1.0-vaapi
    -  gstreamer1.0-x
    -  gstreamer1.0-pipewire
    -  gstreamer1.0-plugins-base
    -  gstreamer1.0-plugins-good
    -  gstreamer1.0-plugins-bad
    -  gstreamer1.0-plugins-ugly
    -  libgpm2
    -  libslang2
    -  libicu74
    -  libtinyxml2-10
    -  pciutils
    override-prime: |
       craftctl default
       # try remove execstack on armhf
       for f in usr/lib/arm-linux-gnueabihf/libde265.so.0.1.8 usr/lib/arm-linux-gnueabihf/libmpeg2.so.0.1.0 usr/lib/arm-linux-gnueabihf/libdirect-1.7.so.7.0.0; do
         if [ -f $f ]; then
           execstack -c $f
         fi
       done

  gpu-2404:
    after: [vimix-binary]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
    - bin/gpu-2404-wrapper
